DOCUMENT_TYPES = [
    {
        "id": "po",
        "label": "Purchase Order",
        "fields": [
            {"name": "vendor_name", "label": "Vendor Name", "type": "text", "required": True},
            {"name": "vendor_address", "label": "Vendor Address", "type": "textarea", "required": True},
            {"name": "vendor_gstin", "label": "Vendor GSTIN", "type": "text", "required": False},
            {"name": "vendor_pan", "label": "Vendor PAN", "type": "text", "required": False},
            {"name": "issuing_company_name", "label": "Deliver To (Company Name)", "type": "text", "required": True},
            {"name": "issuing_company_address", "label": "Deliver To (Company Address)", "type": "textarea", "required": False},
            {"name": "trainer_name", "label": "Trainer / Consultant Name", "type": "text", "required": True},
            {"name": "trainer_address", "label": "Trainer Address", "type": "textarea", "required": False},
            {"name": "technology", "label": "Technology / Batch", "type": "text", "required": True},
            {"name": "po_number", "label": "PO Number", "type": "text", "required": True},
            {"name": "po_date", "label": "PO Date", "type": "date", "required": True},
            {"name": "start_date", "label": "Training Start Date", "type": "date", "required": True},
            {"name": "end_date", "label": "Training End Date", "type": "date", "required": True},
            {"name": "location", "label": "Location of Training", "type": "text", "required": False},
            {"name": "qty", "label": "Quantity (Days)", "type": "number", "required": True},
            {"name": "rate", "label": "Rate", "type": "number", "required": True},
            {"name": "total", "label": "Total Amount", "type": "number", "required": True},
        ],
    },
    {
        "id": "mou",
        "label": "Memorandum of Understanding",
        "fields": [
            {"name": "mou_date", "label": "Agreement Date", "type": "date", "required": True},
            {"name": "vendor_name", "label": "Other Company Name", "type": "text", "required": True},
            {"name": "vendor_address", "label": "Other Company Address", "type": "textarea", "required": True},
            {"name": "vendor_pan", "label": "Other Company PAN", "type": "text", "required": False},
            {"name": "vendor_aadhaar", "label": "Trainer Aadhaar / Phone Number", "type": "text", "required": False},
            {"name": "vendor_signatory_name", "label": "Other Company Signatory Name", "type": "text", "required": True},
            {"name": "vendor_signatory_title", "label": "Other Company Signatory Title", "type": "text", "required": True},
            {"name": "vendor_email", "label": "Other Company Email", "type": "text", "required": True},
            {"name": "trainer_name", "label": "Trainer Name", "type": "text", "required": True},
        ],
    },
    {
        "id": "invoice",
        "label": "Trainer Invoice (Blank Template)",
        "fields": [
            {"name": "trainer_name", "label": "Trainer Name", "type": "text", "required": True},
            {"name": "po_number", "label": "Purchase Order Number", "type": "text", "required": True},
            {"name": "technology", "label": "Technology / Subject", "type": "text", "required": False},
            {"name": "num_rows", "label": "Number of Blank Item Rows", "type": "number", "required": False},
        ],
    },
    {
        "id": "certificate",
        "label": "Internship Certificate",
        "fields": [
            {"name": "intern_name", "label": "Intern Name", "type": "text", "required": True},
            {"name": "student_id", "label": "Student ID / Roll Number", "type": "text", "required": True},
            {"name": "degree_year", "label": "Degree & Year", "type": "text", "required": True},
            {"name": "institution_name", "label": "Institution Name", "type": "text", "required": True},
            {"name": "institution_location", "label": "Institution Location", "type": "text", "required": True},
            {"name": "start_date", "label": "Internship Start Date", "type": "text", "required": True},
            {"name": "duration", "label": "Duration", "type": "text", "required": True},
            {
                "name": "contribution_summary",
                "label": "Contribution Summary",
                "type": "textarea",
                "required": True,
                "placeholder": "Wrap key phrases in **double asterisks** to make them bold. Example: developing an **AI-powered application** to mask PII from resumes, classifying vendors and trainers through AI/ML based on WhatsApp chats, and scraping training titles using machine learning"
            },
            {"name": "certificate_date", "label": "Certificate Issue Date", "type": "date", "required": True, "defaultToday": True},
        ],
    },
    {
        "id": "email",
        "label": "Email Template",
        "fields": [
            {"name": "trainer_name", "label": "Trainer Name", "type": "text", "required": True},
            {"name": "training_date", "label": "Training Date", "type": "date", "required": True},
            {"name": "training_time", "label": "Training Time", "type": "text", "required": True},
            {"name": "meeting_link", "label": "Meeting Link", "type": "text", "required": False},
            {"name": "pay_details", "label": "Pay Details", "type": "text", "required": True},
        ],
    },
]