DOCUMENT_TYPES = [
    {
        "id": "po",
        "label": "Purchase Order",
        "fields": [
            {"name": "issuing_company_name", "label": "Client / Institution Name", "type": "text", "required": True},
            {"name": "issuing_company_address", "label": "Client / Institution Address", "type": "textarea", "required": False},
            {"name": "institution_gstin", "label": "Client GSTIN", "type": "text", "required": False},
            {"name": "institution_pan", "label": "Client PAN", "type": "text", "required": False},
            {"name": "trainer_name", "label": "Trainer / Consultant Name", "type": "text", "required": True},
            {"name": "trainer_email", "label": "Trainer / Consultant Email", "type": "text", "required": False},
            {"name": "technology", "label": "Technology / Batch", "type": "text", "required": True},
            {"name": "po_number", "label": "PO Number", "type": "text", "required": True},
            {"name": "po_date", "label": "PO Date", "type": "date", "required": True},
            {"name": "start_date", "label": "Training Start Date", "type": "date", "required": True},
            {"name": "end_date", "label": "Training End Date", "type": "date", "required": True},
            {"name": "location", "label": "Location of Training", "type": "text", "required": False},
            {"name": "qty", "label": "Quantity (Days)", "type": "number", "required": True},
            {"name": "rate", "label": "Rate", "type": "number", "required": True},
            {"name": "total", "label": "Total Amount", "type": "number", "required": True},
        ],
    },
    {
        "id": "mou",
        "label": "Memorandum of Understanding",
        "fields": [
            {"name": "mou_date", "label": "MoU Date", "type": "date", "required": True},
            {"name": "first_party_full_name", "label": "Full Legal Company Name", "type": "text", "required": True},
            {"name": "first_party_address", "label": "First Party — Address", "type": "textarea", "required": True},
            {"name": "first_party_signatory_name", "label": "First Party — Signatory Name (e.g. Mr. John Doe)", "type": "text", "required": True},
            {"name": "first_party_short_name", "label": "First Party — Short Name (used throughout the MoU, e.g. \"Syasan\")", "type": "text", "required": True},
            {"name": "first_party_sig_name", "label": "Signature Block — Name", "type": "text", "required": True},
            {"name": "first_party_sig_designation", "label": "Signature Block — Designation", "type": "text", "required": True},
            {"name": "first_party_sig_date", "label": "Signature Block — Date", "type": "date", "required": True},
            {"name": "first_party_sig_place", "label": "Signature Block — Place", "type": "text", "required": True},
            {"name": "aca_sig_date", "label": "ACA Signature Date", "type": "date", "required": True},
            {"name": "witness1_name", "label": "Witness 1 — Name", "type": "text", "required": True},
            {"name": "witness1_address", "label": "Witness 1 — Address", "type": "textarea", "required": True},
            {"name": "witness2_name", "label": "Witness 2 — Name", "type": "text", "required": True},
            {"name": "witness2_address", "label": "Witness 2 — Address", "type": "textarea", "required": True},
        ],
    },
    {
        "id": "invoice",
        "label": "Trainer Invoice (Blank Template)",
        "fields": [
            {"name": "trainer_name", "label": "Trainer Name", "type": "text", "required": True},
            {"name": "po_number", "label": "Purchase Order Number", "type": "text", "required": True},
            {"name": "invoice_number", "label": "Invoice Number", "type": "text", "required": True},
            {"name": "invoice_date", "label": "Invoice Date", "type": "date", "required": True, "defaultToday": True},
            {"name": "technology", "label": "Technology / Subject", "type": "text", "required": False},
            {"name": "attended_dates", "label": "Training Days Attended", "type": "multidate", "required": False},
            {"name": "num_rows", "label": "Number of Blank Item Rows", "type": "number", "required": False},
        ],
    },
    {
        "id": "email",
        "label": "Email Template",
        "fields": [
            {"name": "trainer_name", "label": "Trainer Name", "type": "text", "required": True},
            {"name": "training_date", "label": "Training Date", "type": "date", "required": True},
            {"name": "training_time", "label": "Training Time", "type": "text", "required": True},
            {"name": "meeting_link", "label": "Meeting Link", "type": "text", "required": False},
            {"name": "pay_details", "label": "Pay Details", "type": "text", "required": True},
        ],
    },
]